#!/bin/bash


BASEDIR=${1:-$(pwd)}
CONTAINER=$(basename $BASEDIR)

docker stop $CONTAINER
docker rm $CONTAINER

# launch new
docker run -d \
--volume ${HOME}/dockerout/qwfwd-alpine:/home/builduser \
--name $CONTAINER \
$CONTAINER:latest

docker logs --follow $CONTAINER
